# Generated by Django 4.1.6 on 2023-02-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_form1a_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1a',
            name='stream',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
