# Generated by Django 4.1.6 on 2023-02-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_form1a_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1a',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
