# Generated by Django 4.1.6 on 2023-02-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_form1a_contact_alter_form1a_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1a',
            name='contact',
            field=models.CharField(error_messages={'required': 'Enter a value for this contact field.'}, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='form1a',
            name='email',
            field=models.EmailField(error_messages={'required': 'Enter a value for this email field.'}, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='form1a',
            name='name',
            field=models.CharField(error_messages={'required': 'Enter a value for this name field.'}, max_length=100, null=True),
        ),
    ]
